---
# create_rke_cluster_yml/tasks/main.yml

- name: 'Create a cluster.yml'
  ansible.builtin.template:
    src: 'cluster.yml.j2'
    dest: "{{ path_to_cluster_yml }}"
    owner: "{{ cluster_yml_owner | default(omit) }}"
    group: "{{ cluster_yml_group | default(omit) }}"
    mode: "{{ cluster_yml_mode | default(omit) }}"
